import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Topbar from "@/components/topbar";
import SideMenu from "@/components/sidemenu";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} h-screen w-screen flex flex-col`}>
        <ThemeProvider>
          <Topbar />
          <div className="flex flex-1">
            <SideMenu />
            <div className="flex-1 ml-[64px]">
              <main className="h-full">{children}</main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );

}
